use anyhow::Result;
use cell_sdk as cell;
use cell_sdk::membrane::Membrane;
use std::sync::atomic::{AtomicU64, Ordering};
use std::sync::Arc;

struct ExchangeState {
    trade_count: AtomicU64,
    batch_ops: AtomicU64,
}

#[cell::service]
#[derive(Clone)]
struct ExchangeService {
    state: Arc<ExchangeState>,
}

#[cell::handler]
impl ExchangeService {
    /// Place a single order
    async fn place_order(&self, _symbol: String, _amount: u64, _side: u8) -> Result<u64> {
        let id = self.state.trade_count.fetch_add(1, Ordering::Relaxed);
        Ok(id)
    }

    /// Submit a batch of orders for high-throughput testing
    async fn submit_batch(&self, count: u32) -> Result<u64> {
        // Fast path logic: Reserve a range of IDs
        let start = self.state.trade_count.fetch_add(count as u64, Ordering::Relaxed);
        let ops = self.state.batch_ops.fetch_add(1, Ordering::Relaxed);
        
        // Log only every 10,000 batches to avoid I/O bottleneck
        if ops % 10_000 == 0 {
             println!("[Exchange] Processed {} batches (Total trades: {})", ops, start + count as u64);
        }
        
        Ok(start + count as u64)
    }

    /// Return the total number of trades processed
    async fn snapshot(&self) -> Result<u64> {
        Ok(self.state.trade_count.load(Ordering::Relaxed))
    }
}

#[tokio::main]
async fn main() -> Result<()> {
    let state = Arc::new(ExchangeState {
        trade_count: AtomicU64::new(0),
        batch_ops: AtomicU64::new(0),
    });

    let service = ExchangeService { state };

    println!("[Exchange] Online. Fingerprint: 0x{:x}", ExchangeService::SCHEMA_FINGERPRINT);
    println!("[Exchange] Ready for benchmarking (Logs dampened).");

    Membrane::bind("exchange", move |vesicle| {
        let mut s = service.clone();
        async move {
            // The handle_cell_message method is generated by the #[cell::handler] macro
            // It handles deserialization, method dispatch, and serialization of the result.
            let bytes = s.handle_cell_message(vesicle.as_slice()).await?;
            Ok(cell_sdk::vesicle::Vesicle::wrap(bytes))
        }
    }, Some(ExchangeService::CELL_GENOME.to_string())).await
}