use anyhow::Result;
use cell_sdk::{service, handler, protein, Runtime};
use cell_model::macro_coordination::{MacroInfo, MacroKind};
use dashmap::DashMap;
use std::sync::Arc;
use tracing::info;

// --- DNA ---
#[protein]
pub enum Asset { USD, BTC }

// --- LOGIC ---

struct LedgerState {
    accounts: DashMap<u64, DashMap<String, u64>>,
}

#[service]
#[derive(Clone)]
struct LedgerService {
    state: Arc<LedgerState>,
}

#[handler]
impl LedgerService {
    async fn deposit(&self, user: u64, asset: Asset, amount: u64) -> Result<u64> {
        let key = format!("{:?}", asset);
        let user_map = self.state.accounts.entry(user).or_insert_with(DashMap::new);
        let mut bal = user_map.entry(key).or_insert(0);
        *bal += amount;
        info!("[Ledger] Deposit: User {} +{} {:?}", user, amount, asset);
        Ok(*bal)
    }

    async fn lock_funds(&self, user: u64, asset: Asset, amount: u64) -> Result<bool> {
        let key = format!("{:?}", asset);
        if let Some(user_map) = self.state.accounts.get_mut(&user) {
            if let Some(mut bal) = user_map.get_mut(&key) {
                if *bal >= amount {
                    *bal -= amount;
                    info!("[Ledger] Locked: User {} -{} {:?}", user, amount, asset);
                    return Ok(true);
                }
            }
        }
        Ok(false)
    }
}

#[tokio::main]
async fn main() -> Result<()> {
    tracing_subscriber::fmt().init();
    info!("[Ledger] Online");
    
    let service = LedgerService { state: Arc::new(LedgerState { accounts: DashMap::new() }) };

    // Define macros provided by this Cell
    let macros = vec![
        MacroInfo {
            name: "table".to_string(),
            kind: MacroKind::Attribute,
            description: "Creates a database table".to_string(),
            dependencies: vec![],
        },
    ];

    // Expansion Logic (Mocked)
    let expander = |name: &str, _context: &cell_model::macro_coordination::ExpansionContext| -> std::pin::Pin<Box<dyn std::future::Future<Output = Result<String>> + Send>> {
        let name_owned = name.to_string();
        Box::pin(async move {
            if name_owned == "table" {
                Ok("// Generated by Ledger Cell: Table Logic would go here".to_string())
            } else {
                Err(anyhow::anyhow!("Unknown macro"))
            }
        })
    };

    // Explicitly typed call to resolve inference issues
    Runtime::ignite_with_coordination::<_, LedgerServiceProtocol, LedgerServiceResponse, _>(
        move |req| {
            let svc = service.clone();
            Box::pin(async move { svc.dispatch(req).await })
        },
        "ledger",
        macros,
        expander
    ).await
}