[package]
name = "player"
version = "0.1.0"
autostart = true

[neighbors]
renderer = "../renderer"
orbital = "../orbital"
physics = "../physics"
world = "../world"
inventory = "../inventory"
factory = "../factory"
ui = "../ui"
asteroid = "../asteroid"
