// SPDX-License-Identifier: MIT
// cell-build/tests/macro_runner_test.rs
//! Tests for the MacroRunner compilation and caching system.

use cell_build::MacroRunner;
use std::collections::hash_map::DefaultHasher;
use std::fs;
use std::hash::{Hash, Hasher};
use std::path::PathBuf;

/// Create a mock cell in the registry for testing
///
/// NOTE: This creates a minimal mock that can be found by MacroRunner.
/// The actual compilation test is complex because MacroRunner tries to
/// compile the cell as a dependency, which requires a full valid crate structure.
fn setup_mock_cell(name: &str) -> PathBuf {
    let home = dirs::home_dir().unwrap();
    let registry = home.join(".cell/registry").join(name);

    fs::create_dir_all(&registry).unwrap();
    fs::create_dir_all(registry.join("src")).unwrap();

    // Create Cell.toml with macro definition
    let cell_toml = format!(
        r#"
[package]
name = "{}"
version = "0.1.0"
edition = "2021"

[lib]
name = "{}"
crate-type = ["lib"]

[macros]
test_feature = "generate_test_code"
"#,
        name, name
    );

    fs::write(registry.join("Cell.toml"), cell_toml).unwrap();

    // Create lib.rs with macro function - must be valid Rust
    let lib_rs = r#"
//! Mock cell for testing

use proc_macro2::TokenStream;
use quote::quote;
use syn::ItemStruct;

/// Generate test code for the expand macro
pub fn generate_test_code(_item: &ItemStruct) -> TokenStream {
    // Generate a simple implementation
    quote! {
        impl Test {
            pub fn generated_method(&self) -> &'static str {
                "Generated by macro!"
            }
        }
    }
}
"#;

    fs::write(registry.join("src/lib.rs"), lib_rs).unwrap();

    // Create a minimal Cargo.toml for the cell itself
    let cargo_toml = format!(
        r#"
[package]
name = "{}"
version = "0.1.0"
edition = "2021"

[dependencies]
proc-macro2 = "1.0"
quote = "1.0"
syn = {{ version = "2.0", features = ["full"] }}
"#,
        name
    );

    fs::write(registry.join("Cargo.toml"), cargo_toml).unwrap();

    registry
}

fn cleanup_mock_cell(name: &str) {
    let home = dirs::home_dir().unwrap();
    let registry = home.join(".cell/registry").join(name);
    let _ = fs::remove_dir_all(&registry);

    let cache = home.join(".cell/cache/macros").join(name);
    let _ = fs::remove_dir_all(&cache);

    // Also clean up temp directories
    let temp = std::env::temp_dir();
    let entries: Vec<_> = match fs::read_dir(&temp) {
        Ok(entries) => entries.filter_map(|e| e.ok()).collect(),
        Err(_) => return,
    };

    for entry in entries {
        let name_str = entry.file_name().to_string_lossy().to_string();
        if name_str.starts_with("compile_cell_macro_") {
            let _ = fs::remove_dir_all(entry.path());
        }
    }
}

/// Compute hash using std::hash (same logic as MacroRunner)
fn compute_hash_std(path: &PathBuf) -> String {
    let mut hasher = DefaultHasher::new();

    for entry in walkdir::WalkDir::new(path)
        .into_iter()
        .filter_map(|e| e.ok())
    {
        if entry
            .path()
            .extension()
            .map_or(false, |ext| ext == "rs" || ext == "toml")
        {
            if let Ok(bytes) = fs::read(entry.path()) {
                bytes.hash(&mut hasher);
            }
        }
    }

    format!("{:016x}", hasher.finish())
}

#[test]
fn test_compute_hash_consistency() {
    // Test that hash computation is deterministic

    let temp_dir = std::env::temp_dir().join("cell-hash-test");
    fs::create_dir_all(&temp_dir).unwrap();
    fs::create_dir_all(temp_dir.join("src")).unwrap();

    fs::write(temp_dir.join("src/lib.rs"), "pub fn test() {}").unwrap();
    fs::write(temp_dir.join("Cargo.toml"), "[package]\nname = \"test\"").unwrap();

    // Compute hash twice, should be identical
    let hash1 = compute_hash_std(&temp_dir);
    let hash2 = compute_hash_std(&temp_dir);

    assert_eq!(hash1, hash2, "Hash should be deterministic");

    // Modify file, hash should change
    fs::write(temp_dir.join("src/lib.rs"), "pub fn test() { modified }").unwrap();
    let hash3 = compute_hash_std(&temp_dir);

    assert_ne!(hash1, hash3, "Hash should change when content changes");

    // Cleanup
    let _ = fs::remove_dir_all(&temp_dir);
}

#[test]
fn test_cache_invalidation() {
    // Test that cache is invalidated when source changes
    //
    // NOTE: This test verifies the caching logic but doesn't actually
    // compile the macro runner (which would require a full cargo build).
    // We test the hash computation and cache file management instead.

    let cell_name = "test-cache-cell";
    let _guard = scopeguard::guard(cell_name, |name| cleanup_mock_cell(name));

    let cell_path = setup_mock_cell(cell_name);

    // Compute initial hash
    let hash1 = compute_hash_std(&cell_path);

    // Modify source
    let new_lib = r#"
//! Modified mock cell

use proc_macro2::TokenStream;
use quote::quote;
use syn::ItemStruct;

pub fn generate_test_code(_item: &ItemStruct) -> TokenStream {
    quote! {
        impl Test {
            pub fn generated_method(&self) -> &'static str {
                "Modified version!"
            }
        }
    }
}
"#;
    fs::write(cell_path.join("src/lib.rs"), new_lib).unwrap();

    // Compute new hash - should be different
    let hash2 = compute_hash_std(&cell_path);

    assert_ne!(hash1, hash2, "Hash should change when source is modified");

    // Verify cache directory structure would work
    let home = dirs::home_dir().unwrap();
    let cache_dir = home
        .join(".cell/cache/macros")
        .join(cell_name)
        .join("test_feature");
    fs::create_dir_all(&cache_dir).unwrap();

    let bin_path = cache_dir.join("runner");
    let hash_path = cache_dir.join("source.hash");

    // Write fake cache entries
    fs::write(&hash_path, &hash1).unwrap();
    fs::write(&bin_path, "fake binary").unwrap();

    // Verify cache exists
    assert!(hash_path.exists());
    assert!(bin_path.exists());

    // Simulate cache miss (hash changed)
    let cached_hash = fs::read_to_string(&hash_path).unwrap();
    assert_ne!(
        cached_hash, hash2,
        "Cached hash should differ from new hash"
    );

    // This would trigger recompilation in real scenario
    println!("✅ Cache invalidation logic verified");
    println!("   Old hash: {}", hash1);
    println!("   New hash: {}", hash2);
    println!("   Cache would be invalidated: {}", cached_hash != hash2);
}

#[test]
fn test_missing_cell_error() {
    // Test error handling for non-existent cells

    let result = MacroRunner::run("nonexistent-cell-xyz", "feature", "struct Test {}");

    assert!(result.is_err());
    let err = result.unwrap_err().to_string();
    assert!(
        err.contains("not found in registry"),
        "Error should indicate cell not found: {}",
        err
    );
}

#[test]
fn test_missing_macro_feature() {
    // Test error when cell exists but feature doesn't

    let cell_name = "test-missing-feature-cell";
    let _guard = scopeguard::guard(cell_name, |name| cleanup_mock_cell(name));

    setup_mock_cell(cell_name);

    // Try to use non-existent feature
    let result = MacroRunner::run(cell_name, "nonexistent_feature", "struct Test {}");

    assert!(result.is_err());
    let err = result.unwrap_err().to_string();
    assert!(
        err.contains("does not export macro feature"),
        "Error should indicate missing feature: {}",
        err
    );
}

/// Integration test that actually tries to compile a macro runner
///
/// This test is marked as `#[ignore]` because it requires:
/// 1. A properly structured cell in the registry
/// 2. Network access to download dependencies
/// 3. Significant time to compile
///
/// Run with: `cargo test -p cell-build --test macro_runner_test -- --ignored`
#[test]
#[ignore]
fn test_full_macro_runner_compilation() {
    // This would test the full compilation flow
    // Requires a real, working cell in ~/.cell/registry/

    let cell_name = "schema-hub"; // Use a real cell if available
    let home = dirs::home_dir().unwrap();
    let cell_path = home.join(".cell/registry").join(cell_name);

    if !cell_path.exists() {
        println!("Skipping: Real cell '{}' not found in registry", cell_name);
        return;
    }

    let result = MacroRunner::run(cell_name, "table", "pub struct Test { id: u64 }");

    match result {
        Ok(code) => {
            println!("✅ Compilation successful!");
            println!("Generated {} bytes of code", code.len());
            assert!(!code.is_empty());
        }
        Err(e) => {
            // Compilation might fail due to missing dependencies, etc.
            // but we should get a coherent error message
            println!("Compilation failed (expected in test env): {}", e);
        }
    }
}
